### ISSUE TITLE
Error saving message on Burp

### ISSUE THREAD

**Issue by GRodrig** [nccgroup/blackboxprotobuf#23]
```
{"26": {
    "name": "", 
    "type": "message", 
    "field_order": [
        [
            "1", 
            0
        ], 
        [
            "2", 
            0
        ]
    ], 
    "message_typedef": {
        "1": {
            "name": "", 
            "type": "string", 
            "example_value_ignored": "test"
        }, 
        "2": {
            "name": "", 
            "type": "int", 
            "example_value_ignored": 0
        }
    }
}}
```
Can't save/validate this message on burp. 
Says "Error validating type. '26'"

**Comment by rwinkelmaier-ncc** [comment]
Hi! Thanks for submitting this bug. I think I identified a dictionary lookup in the validation function that could trigger this and just pushed https://github.com/nccgroup/blackboxprotobuf/commit/0ed0e3a5d62d9fba4904e55f43532f3170b1d949 to fix this issue.

Let me know if you get an error with that update!

**Comment by GRodrig** [comment]
Working as expected, ty!
