### ISSUE TITLE
Awesome tool

### ISSUE THREAD

**Issue by mdulin2** [nccgroup/blackboxprotobuf#27]
Too many 'issues' are actually issues. Just wanted to say thanks for building this! Made some pentesting jobs much easier on me having this in Burp suite.

I tried finding you on Twitter but couldn't find ya. So, here's my appreciation!

**Comment by rwinkelmaier-ncc** [comment]
Thanks! That's great to hear! It's easy to fall into thinking that no one is using the tool, or only people using the tool run into bugs and give up.

Knowing folks are getting good use out of it makes the effort worth it and helps me allocate more time to improving the tool.
