### ISSUE TITLE
Decoding not consistent

### ISSUE THREAD

**Issue by ashhad** [nccgroup/blackboxprotobuf#3]
Hi,

I was using this extension to decode data being sent in the protobuf format. My Content-Type is application/x-protobuf.

I noticed that the extension gave an error for all the requests, except one. FOr that one request it was able to parse the data while for all other it gave "Error parsing protobuf"

Can you please suggest a fix for this at the earliest ?

**Comment by rwinkelmaier-ncc** [comment]
Sorry for the delay. "Error parsing protobuf" means that the library could not come up with a way to decode the message. It could be something corrupted in the protobuf message, or some variation of protobuf (eg. the message has a length prefix). If you're still having an issue, or run into another issue in the future, could you post the hex/base64 encoded message (if there is no personal information) and the error log from the extension in Burp? It's under Extender -> Extensions -> BlackBoxProtobuf -> Errors.
