### ISSUE TITLE
java.lang.Exception: Failed to load Python interpreter from Jython JAR file in Burp v2020.7

### ISSUE THREAD

**Issue by jonluca** [nccgroup/blackboxprotobuf#4]
<img width="1920" alt="Screen Shot 2020-07-22 at 9 20 28 PM" src="https://user-images.githubusercontent.com/13029040/88249267-2f8ec080-cc61-11ea-909a-18e298bc98e5.png">

I get the above error. I have jython installed through brew, and it works normally

**Comment by jonluca** [comment]
Fixed it, changed my path from `/usr/local/bin/jython` to the actual jython path (for me it was `/usr/local/Cellar/jython/2.7.2/libexec/jython.jar`).

**Comment by blockchainguard** [comment]
ImportError: No module named six

**Comment by Numenorean** [comment]
> ImportError: No module named six

i have the same

**Comment by rwinkelmaier-ncc** [comment]
It sounds like the Python interpreter isn't able to find one of the dependencies. If it's the Burp plugin w/ Jython, then you need to run `git submodule update --init`, if you're running python, then you need to run `pip install -r lib-requirements.txt`.

This doesn't sound like it's related to the original issue, if the above does not work, could you open a new issue?
